import {default as Article } from './article/Article'
import {default as Header } from  './container/header/Header'
import {default as Brand } from './brand/Brand'
import {default as cta} from './cta/Cta'
import {default as Feature} from './feature/Feature'
import {default as Navbar } from './navbar/Navbar'
import {default as Blog } from './container/blog/Blog'
import {default as Footer } from './container/footer/Footer'
import {default as Gpt } from './container/gpt/Gpt'
import {default as Possibility } from './container/possibility/Possibility'